### ISSUE TITLE
Implement TCP transport

### ISSUE THREAD

**Issue by whir1** [whir1/serilog-sinks-graylog#1]
By request @bennybechdk

**Comment by strainovic** [comment]
Any update on this topic? We're using GELF UDP but we'd like to switch to GELF TCP.

Thanks

**Comment by whir1** [comment]
You are first who asking for tcp, i'l implement it soon as possible

**Comment by whir1** [comment]
wasted in version 2.1.0

**Comment by marcinN90** [comment]
I implemented tcp in my project, however only first log from application goes to Graylog. For  Udp and Http eveything is working fine - all the logs goes to Graylog.

**Comment by whir1** [comment]
version 2.1.1 should help
