### ISSUE TITLE
Boolean property payload does not follow GELF specification

### ISSUE THREAD

**Issue by zaha** [whir1/serilog-sinks-graylog#18]
Hey @whir1,

we just noticed that boolean values are not sent in a valid GELF format. It's rather valid JSON it appears to me. Let me illustrate with two examples.

Current way how booleans are sent:
```
{
    "facility": "GELF",
    "full_message": "Boolean value: True",
    "host": "IT-123",
    "level": 6,
    "short_message": "Boolean value: True",
    "timestamp": 1507288877.785,
    "version": "1.1",
    "_stringLevel": "Information",
    "_BoolValue": true
}
```

How valid GELF should look like:
```
{
    "facility": "GELF",
    "full_message": "Boolean value: True",
    "host": "IT-123",
    "level": 6,
    "short_message": "Boolean value: True",
    "timestamp": 1507288877.785,
    "version": "1.1",
    "_stringLevel": "Information",
    "_BoolValue": "true"
}
```

All values must be wrapped in quotes [according to the specification](http://docs.graylog.org/en/2.3/pages/gelf.html). Graylog will simply drop values that do not follow this.

Cheers
Michael

**Comment by whir1** [comment]
fixed in 5.1.2
