### ISSUE TITLE
Parse failure on DateTime/DateTimeOffset in 1.5.2

### ISSUE THREAD

**Issue by bjn** [whir1/serilog-sinks-graylog#19]
Updated nuget package to v1.5.2 and started to get the parse errors in graylog 

**Logging using**
`_logger.LogInformation("Event {@event}", @event);`

**Event class (with Timestamp)**
`public abstract class Event
    {
        public string EventId { get; set; }
        public DateTime Timestamp { get; set; }

        protected Event(string eventId)
        {
            EventId = eventId;
            Timestamp = DateTime.UtcNow;
        }
    }`

**Error in graylog**
`{"type":"mapper_parsing_exception","reason":"failed to parse [event_Timestamp]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"2017-10-17 07:35:41 +00:00\" is malformed at \" 07:35:41 +00:00\""}}`

This was working fine previously with v1.5.1.
Downgraded now to v1.5.1 and it started working again.

Any breaking changes in v1.5.2?

Cheers
Björn

**Comment by whir1** [comment]
loks like bug =(

**Comment by whir1** [comment]
this is a very strange behavior of the graylog in https://github.com/whir1/serilog-sinks-graylog/issues/18 
I fixed the saving of additional fields for this [specification]( http://docs.graylog.org/en/2.3/pages/gelf.html) 
But it looks like DateTime is processed correctly without quotes. I'll fix it today.
