### ISSUE TITLE
Does the sink respect the setting of MinimumLogEventLevel

### ISSUE THREAD

**Issue by jehof** [whir1/serilog-sinks-graylog#26]
Currently I have the issue that the sink sends messages of severity **Debug** to Graylog even when I configure **minimumLogEventLevel** to **Information**.

My configuration looks like (I have ommitted my real values)
`{
 "Serilog": {
   "MinimumLevel": {
     "Default": "Debug",
     "Override": {
       "Microsoft": "Warning",
       "System": "Warning"
     }
   },
   "Using": ["Serilog.Sinks.Console", "Serilog.Sinks.Graylog"],
   "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "Graylog",
        "Args": {
          "hostnameOrAddress": "0.0.0.0",
          "port": "00000",
          "transportType": "Udp",
          "minimumLogEventLevel ": "Information",
          "facility": "Development"
        }
      }
    ]
 }
}`

Is this the right usage of the *minimumLogEventLevel * or for what purpose should I use this?

**Comment by whir1** [comment]
Hmm *this* config sends Debug events, but it's wrong config.
Just replace "minimumLogEventLevel " to "minimumLogEventLevel". But you can make PR in https://github.com/serilog/serilog-settings-configuration to trim whitespaces in property names

**Comment by jehof** [comment]
Sorry, no. It was my fault. I have failed to see this little small whitespace. Using the correct configuration it works as expected.
