### ISSUE TITLE
Not working with NetFramework 4.7.1 and Newtonsoft.Json 11.0.1

### ISSUE THREAD

**Issue by memosk1000** [whir1/serilog-sinks-graylog#28]
ILspy assembly load log: 
// Detected Target-Framework-Id: .NETFramework,Version=v4.6.1

// Referenced assemblies (in metadata order):
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10
	// Assembly reference loading information:
	// Info: Success - Found in Assembly List

// Serilog.Sinks.Graylog.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=48b89c9554032038 (unresolved)
// Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
	// Assembly reference loading information:
	// There were some problems during assembly reference load, see below for more information!
	// Error: Could not find reference: Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

**Comment by whir1** [comment]
I created a simple console application under 4.7.1, but it works. Could you send me a more detailed example for playback?

[ConsoleApp1.zip](https://github.com/whir1/serilog-sinks-graylog/files/2015528/ConsoleApp1.zip)

**Comment by memosk1000** [comment]
I couldn't reproduce the error in a simple project . Also this ILspy is not reproducing the error . It's basically custom loading into software domain (custom ShadowCopy and LoaderOptimization.MultiDomain ) We solved this with lowering the version to Newtonsoft.Json 10.
