### ISSUE TITLE
Thread pool starvation

### ISSUE THREAD

**Issue by Cwallice** [whir1/serilog-sinks-graylog#29]
Hi 
First I'd like to appreciate your plugin, really good piece of work.

recently I found that my asp.net core app becomes irresponsive under certain load. Usually it happens around 1000 requests per second.

Quick performance review pointed at:
https://github.com/whir1/serilog-sinks-graylog/blob/6d0e3b930fbeedbb56fd3cdb91790f9957b2f298/src/Serilog.Sinks.Graylog/GraylogSink.cs#L30

After taking Task.Run off ( it was doing CPU based async operation ) everything came into normal state.

Should I consider a PR for that?

**Comment by whir1** [comment]
@Cwallice if i am not an idiot this 85a0a7663cb718306b4901c559c68a3b76e30616 commit should help

**Comment by Cwallice** [comment]
@whir1 Hell yes. 
Thx

**Comment by 312k1t** [comment]
Hi @whir1,
I have similar issue (hundreds of requests per second) as @Cwallice, I see that in this commit https://github.com/whir1/serilog-sinks-graylog/commit/85a0a7663cb718306b4901c559c68a3b76e30616 you removed Task.Run, but in this one https://github.com/whir1/serilog-sinks-graylog/commit/c6f6ca0ba89597db5affab1f6260a0bf69ceed2a it's back there.

Can you please let me know what was the reason?
![2019-09-10 15_09_49-JetBrains dotTrace Timeline Viewer](https://user-images.githubusercontent.com/3645776/64616603-30b65680-d3dd-11e9-8180-1128a4df394a.png)

**Comment by whir1** [comment]
should work
