### ISSUE TITLE
Wrong log level mapping!

### ISSUE THREAD

**Issue by hVostt** [whir1/serilog-sinks-graylog#30]
The Verbose level must be greater or at least equal to Debug.

```csharp
        private static readonly Dictionary<LogEventLevel, int> LogLevelMap = new Dictionary<LogEventLevel, int>
        {
            [LogEventLevel.Verbose] = 5, // wrong! must be 7
            [LogEventLevel.Debug] = 7,
            [LogEventLevel.Information] = 6,
            [LogEventLevel.Warning] = 4,
            [LogEventLevel.Error] = 3,
            [LogEventLevel.Fatal] = 0
        };
```

RU: Неправильный код для уровня Verbose, это самый подробный уровень, должен быть больше Debug. Можно поправить?

**Comment by whir1** [comment]
Поменять то можно, но по уровням в [сислоге](http://www.kiwisyslog.com/help/syslog/index.html?protocol_levels.htm) идет 

0 Emergency: system is unusable
1 Alert: action must be taken immediately
2 Critical: critical conditions
3 Error: error conditions
4 Warning: warning conditions
5 Notice: normal but significant condition
6 Informational: informational messages
7 Debug: debug-level messages 

Жалко мапить Verbose и Debug на 7, хотя ты наверное прав. На днях запилю

**Comment by hVostt** [comment]
Да, всё верно, но в сислоге нет Verbose (Trace), а в Serilog и Microsoft.Extensions.Logging нет Notice, Alert. Так как нет возможности задать уровень 8, придётся и Debug и Verbose мапить на Debug, но это по крайне мере не противоречит концепции уровней журналирования. Ещё есть stringLevel, куда будет записано что это Debug или Versbose.

Спасибо! :)

**Comment by whir1** [comment]
потрачено
