### ISSUE TITLE
System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler

### ISSUE THREAD

**Issue by Gosha** [whir1/serilog-sinks-graylog#33]
I'm trying to use this sink in a .NET Core application, but I get this exception when I turn on `Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));` (And no messages sent to Graylog):
```
2018-09-07T13:00:53.4534320Z Oops something going wrong System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at Serilog.Sinks.Graylog.GraylogSink.Emit(LogEvent logEvent)
```

[Reproduction gist](https://gist.github.com/Gosha/e9830617733542fa97bed275f453d303)

Environment:
- OS: macOS High Sierra 10.13.6
  - and docker in a vm
  - and windows 10 in a vm
- .NET Core 2.1

Project file:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>test_dotnet_core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.7.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.Graylog" Version="2.0.2" />
  </ItemGroup>

</Project>
```

**Comment by whir1** [comment]
It fails in TaskScheduler.FromCurrentSynchronizationContext(). But i haven't time to fix it =\

**Comment by whir1** [comment]
you can make PR XD

**Comment by Gosha** [comment]
I would if I had any idea of where to start debugging this. Still a newbie
in .NET..

Den ons 19 sep. 2018 11:04Anton Volkov <notifications@github.com> skrev:

**Comment by salamoun** [comment]
I have same problem:
.NET 4.6 Console App

During emit I get error:
`2018-10-26T11:11:30.0957227Z Oops something going wrong System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
   v System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   v Serilog.Sinks.Graylog.GraylogSink.Emit(LogEvent logEvent)`

Message is already delivered to Graylog server, but this exception happens.

**Comment by whir1** [comment]
can you test this case on 2.0.3 version?

**Comment by salamoun** [comment]
It seems that version 2.0.3 fix the problem. Thanks.
