### ISSUE TITLE
Input new property in the log.

### ISSUE THREAD

**Issue by jpfrezzarin** [whir1/serilog-sinks-graylog#34]
I see that the log sended to graylog has a template, but I need to send the log with a particular property. 

It's possible? Can I set the new property in the appsettings.json?

**Comment by whir1** [comment]
What property you want to send?

In top most scenarios you can use Enrichers.



`
            GraylogSinkOptions graylogSinkOptions = new GraylogSinkOptions
            {
                Facility = "SomeFacility",
                HostnameOrAddress = "graylogserver",
                TransportType = TransportType.Udp,
                Port = 12201
            };
             Log.Logger = new LoggerConfiguration()
                                          .Enrich.FromLogContext()
                                          .MinimumLevel.Verbose()
                                          .WriteTo.Graylog(graylogSinkOptions)
                                          .CreateLogger();


            using (LogContext.PushProperty("PropertyOne", "PropertyOne"))
            using (LogContext.PushProperty("PropertyTwo", "PropertyTwo"))
            {
                   //Many code
                    _logger.Debug("Some value");
            }
`

you also can create property when application start and push it to log context.

**Comment by jpfrezzarin** [comment]
Thanks whir1, it works! :)

I see also that its possible to set a particular property in the moment you are creating the logger, calling this method:

`.Enrich.WithProperty("property", value)`

I need to send a property with the log that's responsible to redirect it internaly in the graylog. This property always will has the same value, so calling the method WithProperty(string, object) will solve my problem!
