### ISSUE TITLE
Не отправляет логи с уровнем логирования Debug, Verbose

### ISSUE THREAD

**Issue by kesyk** [whir1/serilog-sinks-graylog#35]
При следующем коде:
`var loggerConfig = new LoggerConfiguration();

loggerConfig.WriteTo.Graylog(new GraylogSinkOptions{
  Facility = "...",
  TransportType = TransportType.Udp,
  MinimumLogEventLevel = LogEventLevel.Verbose,
  HostnameOrAddress = "...",
  Port = 12205
});

logger.Information("test");
logger.Debug("test");
logger.Verbose("test");`

На сервер Graylog приходят только сообщения с типом Information, Error, Fatal, Warning

**Comment by whir1** [comment]
А в настройках самого серилога тоже minlevel - Verbose? 
Не забывай, что если на самом верхнем уровне логгирования verbose отключен, то эвенты даже не доходят до синка.

**Comment by whir1** [comment]
Ну переписать то в рантайме наверное можно. Вопрос зачем это делать?
Я правильно понимаю, что необходимо, чтобы часть логов писалась в один facility, а часть в другой?

**Comment by kesyk** [comment]
Нет. Есть два конфига appsettings.json(конфига самого приложения:стринги
подключения к бд, месседд-брокерам,аппайди), serilog.json(конфиг логгерам
серилога)
facility грейлога- это тот же аппайди из appsettings.json. Задача :
засетапить аппайди в синк опшинс грейлога как facility без прихода к
мануальному дублированию значения аппайди из appsettings.json в
serilog.json в поле facility

**Comment by whir1** [comment]
Экий вы извращенец. К сожалению не знаю можно ли так сделать в серилоге из коробки. Насколько я помню вся конфигурация серилога считывается через [serilog-settings-configuration](https://github.com/serilog/serilog-settings-configuration) поэтому я бы советовал спросить у них. Лично я таким просто никогда не пользовался

**Comment by whir1** [comment]
в версии 2.0.3 добавил поддержку переменных окружения, как вариант если appid берется из них  - можно то можно прокинуть переменную

**Comment by kesyk** [comment]
Понял. Посмотрю что к чему . Спасибо
