### ISSUE TITLE
Не работает подгрузка конфига из файла appsettings.json

### ISSUE THREAD

**Issue by kesyk** [whir1/serilog-sinks-graylog#36]
Необходимо изменить Using: [ "Serilog.Sinks.Graylog" ] на Using: [ "Serilog.Sinks.Graylog.Core" ]

**Comment by whir1** [comment]
Окай, гляну завтра поближе

**Comment by whir1** [comment]
Хм, посмотрел, необходимо вернуть назад XD использовать Serilog.Sinks.Graylog.Core имхо не гуд

**Comment by whir1** [comment]
в общем вернул неймспейс на место
