### ISSUE TITLE
Missing enrichment data for exceptions

### ISSUE THREAD

**Issue by srollinet** [whir1/serilog-sinks-graylog#39]
Hi,

I try to add exception enrichment data in my logs, using the following lib: https://github.com/RehanSaeed/Serilog.Exceptions
But it seems the related properties are not sent to Graylog. 

I tried to log in a file with a json format and the enrichment is working.
Any reason it doesn't work with Graylog? Am I maybe missing a configuration or something?

**Comment by whir1** [comment]
fixed in version 2.0.6 of main package

**Comment by srollinet** [comment]
Great! I cannot test before next week. I'll confirm you as soon as I can
