### ISSUE TITLE
Changing MaxMessageSizeInUdp 

### ISSUE THREAD

**Issue by oruchreis** [whir1/serilog-sinks-graylog#43]
Hi,
As far as I saw, this library supports maximum 8192 byte of udp packet size. This means 128 * 8192 = 1MB total message size can be sent to gralog, correct me if I'm wrong. But our application keeps very big log data that bigger than 1 mb. Can we change MaxMessageSizeInUdp  in ChunkSettings?

**Comment by whir1** [comment]
Hmmm i can move this to settings, but not today XD

**Comment by whir1** [comment]
fixed in 2.0.8 version
