### ISSUE TITLE
Message template field

### ISSUE THREAD

**Issue by bednart** [whir1/serilog-sinks-graylog#45]
Hi,

I'm using version 2.0.9 for sending logs into Elastic logstash server. Logs works fine but I'm missing message_template field in Elastic to support structured logging. Is there any way how to add original message template to be logged in Elastic? 

For example:
`_logger.LogInformation("Test {TestMessage}.", "HelloWorld");`

should log "Test {TestMessage}." into elastic as message_template.

Thanks,
beda

**Comment by whir1** [comment]
Added configuration parameters IncludeMessageTemplate and MessageTemplateFieldName.

**Comment by bednart** [comment]
Hi,
I have updated Serilog.Sinks.Graylog package to 2.0.10 and added property into appsetting.json:

`{
        "Name": "Graylog",
        "Args": {
          "hostnameOrAddress": "....",
          "port": "12201",
          "transportType": "Udp",
          "includeMessageTemplate": true
        }
      }`

but still there is no message_template in elastic logged messages.

**Comment by whir1** [comment]
i've forgot add parameter to extension method =(, so it's works only when configuring from source code. The new nuget package are building now.

**Comment by bednart** [comment]
It works now ;) Thanks :)
