### ISSUE TITLE
Error use asp.net MVC => when use async, await in Emit

### ISSUE THREAD

**Issue by vonhatnam100689** [whir1/serilog-sinks-graylog#49]
public async void Emit(LogEvent logEvent)
        {
            try
            {
                await EmitAsync(logEvent);
            }
            catch (Exception exc)
            {
                SelfLog.WriteLine("Oops something going wrong {0}", exc);
            }
        }

**Comment by vonhatnam100689** [comment]
=> NOT working asp.net mvc .Net Framework
public async void Emit(LogEvent logEvent)
{
try
{
await EmitAsync(logEvent);
}
catch (Exception exc)
{
SelfLog.WriteLine("Oops something going wrong {0}", exc);
}
}

==> Woking asp.net mvc .Net Framework ( remove async  and await )

public void Emit(LogEvent logEvent)
{
try
{
 EmitAsync(logEvent);
}
catch (Exception exc)
{
SelfLog.WriteLine("Oops something going wrong {0}", exc);
}
}

**Comment by whir1** [comment]
What's mean NOT working? It worked at our productions servers on my job, and it works fine (In MVC / .NetCore, and WinForms applications). If i remove await call then some logs may be missed when application crashes.
