### ISSUE TITLE
Async void Emit - logs sometimes are not send

### ISSUE THREAD

**Issue by robosek** [whir1/serilog-sinks-graylog#51]
Hello!

I experienced some issues with sending logs in my test project. It's just simple console project and last line of code is responsible for sending logs. In most cases logs are not send. I was very confused first time so I investigated sink code and I found [this](https://github.com/whir1/serilog-sinks-graylog/blob/90401bb2e024fc843ca3b3d008284b48df2c728e/src/Serilog.Sinks.Graylog/GraylogSink.cs#L30). I think it's because of `async void Emit` which is basically fire and forget method. According to my knowledge `async void` is construction designed only for event handlers and in others cases may be not stable. IMHO it should be just void method and logs should be send synchronously but correct me if I'm wrong. 

Here are some references: 
1. [Link](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming)
2. [Link ](https://jaylee.org/archive/2012/07/08/c-sharp-async-tips-and-tricks-part-2-async-void.html)

I'm happy to help and do some PR but first I want to know your opinion 😄 

BTW Thanks for great sink! It's fantastic to use composition of graylog and serilog and it's thanks to your work!

**Comment by whir1** [comment]
Маке PR ^^
