### ISSUE TITLE
TCP client doesn't reconnect after a disconnection

### ISSUE THREAD

**Issue by pbr1111** [whir1/serilog-sinks-graylog#57]
Hello, 
I'm using this Sink in different applications and I've found the problem that if the Graylog server has a small connection cut and data is just being sent by the TCP client, this Sink is never able to recover that connection and forces us to restart our applications to be able to log again in Graylog. 

I will perform a PR to handle TCP client reconnections.

**Comment by CarlosLanderas** [comment]
@pbr1111 I think we might be suffering this problem as some applicactions have stopped logging all of a sudden when using TCP input.
