### ISSUE TITLE
Send messages async

### ISSUE THREAD

**Issue by mribichich** [whir1/serilog-sinks-graylog#6]
Hi there, I think it would be great to have a possibility to send messages async. Maybe do it configurable.

Because right now you are sending the message inside a `Task`, but you are waiting on it to finish.

Which practically makes it sync.

``` 
# Serilog.Sinks.Graylog/Transport/Udp/UdpTransportClient.cs

        public void Send(byte[] payload)
        {            
            Task resultTask = Task.Run(() =>
            {
                using (var udpClient = new UdpClient())
                {
                    udpClient.SendAsync(payload, payload.Length, _target);
                }
            });
            resultTask.Wait();
        }
```

I would love to contribute to it. Maybe we could remove the wait or not according to configuration by user

thanks!

**Comment by daningalla** [comment]
+1 on this. Any consideration?

**Comment by whir1** [comment]
I can do it, but after migate to new VS project files

**Comment by whir1** [comment]
implemented
